### ISSUE TITLE
🐞 Year view brokes calendar

### ISSUE THREAD

**Issue by HRandt** [javalent/calendarium#110]
### Check for existing bug reports before submitting.

- [X] I searched for existing Bug Reports and found no similar reports.

### Expected Behavior

Pressing "Year" in the calendar view should show the full calendar (I guess, I never saw it working).

### Current behaviour

When I press "Year", the calendar not only doesn't change the view from week/month to year but it also stop working. I have to close Obsidian and start again.

### Reproduction

1. Create a calendar with 13 months, each month with 2 weeks of 24 days, in case that affects.
2. Press YEAR in the lateral view.
![imagen](https://github.com/javalent/calendarium/assets/66415279/b8e2cee6-0ade-4d41-b81d-2abe2749ab58)

### Which Operating Systems are you using?

- [X] Android
- [ ] iPhone/iPad
- [ ] Linux
- [ ] macOS
- [X] Windows

### Obsidian Version Check

1.5.8

### Plugin Version

1.0.10

### Confirmation

- [ ] I have disabled all other plugins and the issue still persists.

**Comment by valentine195** [comment]
@HRandt can you please open dev tools (ctrl/shift/i) and tell me if there is an error in the dev console?

Also, uploading your custom calendar JSON would be appreciated.

**Comment by valentine195** [comment]
@HRandt is this still an issue?
