### ISSUE TITLE
Calendar does not show at all

### ISSUE THREAD

**Issue by Baqon** [javalent/calendarium#116]
### Check for existing bug reports before submitting.

- [X] I searched for existing Bug Reports and found no similar reports.

### Expected Behavior

After creating a custom calendar, I click the icon on the left side of Obsidian to open the calendar. The calendar opens and is visible.

### Current behaviour

After creating a custom calendar, I click on the icon on the left side of Obsidian to open the calendar. The calendar "opens" (the icon appears on the top bar of Obsidian), but no calendar is visible.
![Calendarium Bug](https://github.com/javalent/calendarium/assets/165096868/db391fb5-0c9e-46d2-9c58-dea2c7ff23f5)

In the Obsidian Developer Console, it shows the following:
`Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'name')
    at eval (plugin:calendarium:419:39474)
    at f (plugin:calendarium:12:9128)
    at eval (plugin:calendarium:12:9242)
    at Object.o [as subscribe] (plugin:calendarium:12:8797)
    at Te (plugin:calendarium:9:24740)
    at le (plugin:calendarium:9:24884)
    at GC (plugin:calendarium:419:46763)
    at se (plugin:calendarium:12:5247)
    at new Vc (plugin:calendarium:419:47861)
    at T0 (plugin:calendarium:423:14129)`

### Reproduction

1. Open Obsidian
2. Click the Calendarium icon on the left
3. Select the Calendarium icon on the top right of Obsidian

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [ ] Linux
- [ ] macOS
- [X] Windows

### Obsidian Version Check

1.5.11

### Plugin Version

1.0.12

### Confirmation

- [X] I have disabled all other plugins and the issue still persists.

**Comment by valentine195** [comment]
@Baqon if this still occurs on the latest version, could you please export your calendar JSON in settings and upload it here?

**Comment by valentine195** [comment]
@Baqon following up again

**Comment by Baqon** [comment]
Yes, everything is working now. Thank you!
