### ISSUE TITLE
🐞 fc-date and fc-end is not being parsed correctly when a custom date format is set with hyphens

### ISSUE THREAD

**Issue by OhMyDeera** [javalent/calendarium#121]
### Check for existing bug reports before submitting.

- [X] I searched for existing Bug Reports and found no similar reports.

### Expected Behavior

Unsure if this is a bug or working as expected.

Changing the date format from YYYY-MM-DD to DD MMM YYYY and updating the `fc-date` and `fc-end` to be in the same format should have only changed the format of the date displayed in the calendar view.

### Current behaviour

Closing and reopening obsidian after changing the format to DD MMM YYYY removes all automatic events from the calendar.

### Reproduction

1. Create a new event using the `fc-calendar`, `fc-date` and `fc-end` frontmatter properties.
2. Go to the calendar settings and change the format of the date to any format without hyphens.
3. At first it will change the format as expected, however when you close obsidian and reopen, you will find that all the automatic events have now gone.
4. Checking the logs you should be able to see errors like so: `Calendarium: Must specify all three segments in DD MMM YYYY order. From 'Sessions/Untitled.md', date value: '24 Aug 0034'`

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [ ] Linux
- [ ] macOS
- [X] Windows

### Obsidian Version Check

1.5.12

### Plugin Version

1.1.0

### Confirmation

- [X] I have disabled all other plugins and the issue still persists.

### Possible solution

update the following line (event-helper.ts [line 346]) to allow space as a separator: 
`let datebits = datestring.split(/(?!^)[-–—](?![^[]*])/);`

I know that you can also use the date object, but I prefer editing the date without having to go into source view.

**Comment by valentine195** [comment]
I did play with this updating this to allow spaces:

```ts
let datebits = datestring.split(/(?!^)[-–—](?![^[]*])/);
```

but unfortunately that ignores other delimiters that could be used in a date format. Realistically I need to actually parse these bits against the format that was specified.

**Comment by OhMyDeera** [comment]
Yeah that's a good point. I only did a quick scan through the code, but can take a more in depth look and try to come up with an actual solution once I've got some time if you'd like. 
One idea could be using RegExp and using the date format supplied in the config to build a dynamic regex to get the day, month and year regardless of what seperators they are using. Though doing so whilst also making sure the recurring dates still parse as expected may prove to be fiddly.

**Comment by ebullient** [comment]
> Yeah that's a good point. I only did a quick scan through the code, but can take a more in depth look and try to come up with an actual solution once I've got some time if you'd like. One idea could be using RegExp and using the date format supplied in the config to build a dynamic regex to get the day, month and year regardless of what seperators they are using. Though doing so whilst also making sure the recurring dates still parse as expected may prove to be fiddly.

I think what would help most is any suggestion of additional tests for formats. ;) we have some, but obviously forgot this one. That way we fix this w/o breaking others.

Iterative lookup instead of a split might be better. Or split based on (any non-word/non-digit character) could also do it. The other option is not to use split at all, but use regex find. We need the first three, and then the starting position of content after that as the ordinal.

**Comment by valentine195** [comment]
@OhMyDeera Unfortunately I have spent quite a bit of time trying to fix this issue but its almost impossible to make this generic.

I am going to update the setting in the creator to reflect that this is for the **Display Date format**, and require dashes when parsing.
