### ISSUE TITLE
Intercalary and Irregular Weekdays Megathread

### ISSUE THREAD

**Issue by sigrunixia** [javalent/calendarium#14]
For @professorpenquin

Hello!

For the calendar I've made, there are 30 days in a month and 7 days in a week, but the 15th and 30th days of that month are special days that fall outside of the normal 7-day week. The way this should look is Mon-Sun, Mon-Sun, 1st Special Day, Mon-Sun, Mon-Sun, 2nd Special Day.

I'm able to make the special day on the 15th work by using Leap-Days, but trying to do that for the 30th runs into one of two issues. If I set the month to have 30 days and that Leap Day to occur on the 30th, then there will be a 31st and 32nd day of the month that I do not want. If I set the month to have 28 days to account for the two leap-days, it will only let me set the Leap day to the 29th and still have extra days. I'm not sure if I am missing something or if this is just something the Fantasy Calendar can't do yet.

Any help is greatly appreciated!

Edit: I managed to find a workaround right after posting this (set the month to 29 days, added a leap day to occur after the 29th, then changing the month to be 28 days). However, this seems to be messing with my moon cycles now. One moon has a 10 day cycle, and the other has a 30 day cycle, so both should be a New Moon on the first of every month since every month is 30 days. But it looks like the moons act weird on those leap-days because every month has the new moons two days later.

Also, there's a blank "week" before each leap day that I don't think should be there? The screen grab attached shows both the blank week before a leap day and how the moon phases seem to shift backward after the Leap Day. The 10 day moon is in green and the 30 day moon is in red.

- [x] Yay
- [ ] Nay
- [ ] Implemented

**Comment by valentine195** [comment]
I believe that this is fixed.
