### ISSUE TITLE
[Feature]:  Era token support 

### ISSUE THREAD

**Issue by ReconVirus** [javalent/calendarium#30]
### Please make sure this feature request hasn't been suggested before.

- [X] I searched previous Issues and didn't find any similar feature requests.

### Feature description

Support for Era [token ](https://momentjs.com/docs/#/displaying/format/)

<html><body>

Era | N, NN, NNN | BC AD         Note: Abbr era name
-- | -- | --
  | NNNN | Before Christ, Anno Domini          Note: Full era name
  | NNNNN | BC AD         Note: Narrow era name

</body>
</html>

### Solution

Is there is an option to add Era naming from fantasy calendar, it should be utilized, this might be useful in timeline creating 

### Alternatives

have a option  to allow Era naming

### Additional Information

era support

**Comment by valentine195** [comment]
Added
