### ISSUE TITLE
[Bug]: 3 Icons

### ISSUE THREAD

**Issue by ProStashio** [javalent/calendarium#36]
### Check for existing bug reports before submitting.

- [X] I searched for existing Bug Reports and found no similar reports.

### Expected Behavior

1 Icon

### Current behaviour

3 Icons

### Reproduction

Install Plugin (Note: This only happened when I installed it and then enabled it. The issue persisted even after closing down Obsidian and reopening. I only got rid of the icons after disabling and re-enabling the plugin)

![image](https://github.com/javalent/the-calendarium/assets/19267479/2669ae4a-44d4-45a2-b675-e3d131d565e1)

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [ ] Linux
- [ ] macOS
- [X] Windows

### Obsidian Version Check

1.3.5

### Plugin Version

1.0.1-b10

### Confirmation

- [x] I have disabled all other plugins and the issue still persists.

**Comment by valentine195** [comment]
Has this occurred since?

**Comment by Wegi** [comment]
I encountered the same problem, but with 6 icons. Let me know, if I can somehow help find the cause.

**Comment by valentine195** [comment]
I believe this behavior is fixed.
