### ISSUE TITLE
[Bug]: Multiple errors for Day and Events

### ISSUE THREAD

**Issue by Yilmas** [javalent/calendarium#44]
### Check for existing bug reports before submitting.

- [X] I searched for existing Bug Reports and found no similar reports.

### Expected Behavior

See below

### Current behaviour

- [x] 1 - Click on "Day" then on the left/right chevrons, the date does not change. But events disappear of the initial day.
![image](https://github.com/javalent/the-calendarium/assets/6323003/e58f1844-d4a9-48be-8d81-21654b1a56b0)

- [X] 2 - If I click on a day in the Month view, and then click on the Day view, I will get 2 day views.
**Fixed in b14**
![image](https://github.com/javalent/the-calendarium/assets/6323003/c9baf5c6-de12-4439-8e96-898e7351d88d)

- [x] 3 - Some events are not colored, even events from the same category.
![image](https://github.com/javalent/the-calendarium/assets/6323003/92fb66b6-e862-483e-bf0c-4117bf08f7a9)

- [ ] 4 - Events that span several days are only shown on the initial day.
![image](https://github.com/javalent/the-calendarium/assets/6323003/217e1530-ee68-4c8e-942e-6a7d1ade9b3d)

- [x] 5 - When changing the month, and go back to the initial month (using the chevrons), the day will not longer display events. Even if you click on a day in the month view.
![image](https://github.com/javalent/the-calendarium/assets/6323003/40bdc5c7-8042-45ae-b6c5-324cb3d1c766)

- [x] 6 - When clicking on a day with events, and then click on another day with events. The following error is displayed in the console.
![image](https://github.com/javalent/the-calendarium/assets/6323003/a4aa903c-2cd8-4957-b2a4-15529f565d8c)

- [x] 7 - See comment: https://github.com/javalent/the-calendarium/issues/44#issuecomment-1697020135

- [x] 8 - See comment: https://github.com/javalent/the-calendarium/issues/44#issuecomment-1698557930

### Reproduction

See above

### Which Operating Systems are you using?

- Android
- iPhone/iPad
- Linux
- macOS
- [X] Windows

### Obsidian Version Check

Latest

### Plugin Version

b12

### Confirmation

- [X] I have disabled all other plugins and the issue still persists.

### Possible solution

Note this is with a custom calendar, migrated from FC.

**Comment by Suleiman212** [comment]
I'm having most of these same issues. Most notable is events only appearing the first time you select a day in the side panel, once you move off the day or click the arrows to go to a different month/week, events no longer appear in the day view brought up by clicking on days with events, although the dots indicating the events still show within the month/week view itself.

**Comment by Yilmas** [comment]
Edited with tasks to easier show which issues has been fixed.

**Comment by mProjectsCode** [comment]
There is also an error that appears in the console when you click on an event.

**Comment by Yilmas** [comment]
1, 5, and 6 has been solved in b15-b18.

**Comment by Yilmas** [comment]
New bug discovered.

- [ ] When clicking a day with events, then clicking on a day without, the events from the first day does not disappear. (The event window only updates when events are present on a date)

**Comment by Yilmas** [comment]
3 and 7 fixed in b21. 

New issue: 
- [ ] Events found in notes are not saved across loads. However, they are added on initial search.

**Comment by Yilmas** [comment]
8 is fixed in b22

**Comment by valentine195** [comment]
I believe all issues are fixed now?

Please re-open if that is not the case.
