### ISSUE TITLE
Week Overflow not working correctly

### ISSUE THREAD

**Issue by Meese419** [javalent/calendarium#88]
### Check for existing bug reports before submitting.

- [X] I searched for existing Bug Reports and found no similar reports.

### Expected Behavior

I should have 1 month of 42 days in 6 full weeks. Then a month of two days on their own followed by another month of 42 days starting on the first day of the week

### Current behaviour

It is including the two days as part of the week even though week overflow is turned off. So if month 1 ends at the end of the week the 2 day period starts on the 1 of the next and the month following that starts on the third.

### Reproduction

1. Import calendar from fantasy maps that has overflow turned off
2. Load calendar in Calendarium with overflow turned off

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [ ] Linux
- [ ] macOS
- [X] Windows

### Obsidian Version Check

1.5.3

### Plugin Version

1.0

### Confirmation

- [ ] I have disabled all other plugins and the issue still persists.

**Comment by valentine195** [comment]
@Meese419 Is this still an issue?
