### ISSUE TITLE
Orbits/Cycles Megathread

### ISSUE THREAD

**Issue by sigrunixia** [javalent/calendarium#9]
## Moons
From @bachman75

Would it be possible to implement partial days for the moon cycles? For instance, the calendar for Hyperborea has two moons. One has a 7 day cycle and the other has a 45.5 day cycle. With 13 months of 28 days each, that means both moons are simultaneously full every 91 days.
Currently, I can use a calendar event for the second moon, so it's not a huge deal, but it would be a very handy feature.

Thank you very much for all your hard work on this and your other plugins!!

- [x] Yay
- [ ] Nay
- [ ] Implemented

**Comment by sigrunixia** [comment]
## Eras

For @8null8, @GermanNr4, @missymissprim, and @pwkooij
Would love it if the calander displayed the era year instead of the actual year, along with the ability to hover over it to see the full year

---

**Comment by valentine195** [comment]
You can use partial days for the moon cycles, not sure this is actually an issue.

**Comment by bachman75** [comment]
I'm still not able to use partial days for the lunar cycle.  Entering "45.5" causes the box to turn red.  Is there another way to enter a half day?
