### ISSUE TITLE
🐞 Unable to create Events or Event Categories

### ISSUE THREAD

**Issue by eedy-reedy** [javalent/calendarium#97]
### Check for existing bug reports before submitting.

- [X] I searched for existing Bug Reports and found no similar reports.

### Expected Behavior

When clicking on the '+' icon below categories/events in the new GUI, a new event should have appeared with the ability to edit name, description, and time.

### Current behaviour

There was no response; the '+' button could be clicked, but a new category/event was not created from it.

### Reproduction

- Launch (synced) Obsidian vault
- Enter settings
- Select Calendarium
- Click on wrench icon next to existing calendar
- Select "Events" tab
- Enter name of event in "Add new" field
- Click on '+' button

No further response. It doesn't work when creating a new calendar, although the templates still function properly.

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [ ] Linux
- [ ] macOS
- [X] Windows

### Obsidian Version Check

1.5.8

### Plugin Version

1.0.2

### Confirmation

- [X] I have disabled all other plugins and the issue still persists.

**Comment by valentine195** [comment]
This should be fixed, I believe. Please re-open if that is not the case.
